"""Create All

Revision ID: 06cafd08db47
Revises: ddf09c511f32
Create Date: 2025-07-27 18:54:11.523013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cafd08db47'
down_revision: Union[str, Sequence[str], None] = 'ddf09c511f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('silver_story_chunks', 'dialogue_ratio')
    op.drop_column('silver_story_chunks', 'embedding_model_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silver_story_chunks', sa.Column('embedding_model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('silver_story_chunks', sa.Column('dialogue_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
