"""Deleted embedding_model in silver_story_chunks

Revision ID: aeff7c300d7b
Revises: 06cafd08db47
Create Date: 2025-07-27 18:58:33.396931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeff7c300d7b'
down_revision: Union[str, Sequence[str], None] = '06cafd08db47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_silver_chunks_embedding_model'), table_name='silver_story_chunks')
    op.drop_column('silver_story_chunks', 'embedding_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('silver_story_chunks', sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_silver_chunks_embedding_model'), 'silver_story_chunks', ['embedding_model'], unique=False)
    # ### end Alembic commands ###
